### ISSUE TITLE
Problem with juliadoc when building with --HEAD

### ISSUE THREAD

**Issue by bosmacs** [staticfloat/homebrew-julia#135]
When (re)installing julia via `brew reinstall julia --HEAD`, I receive an error: `fatal: repository 'doc/juliadoc' does not exist`. Looking at the formula, it appears there is a mistake:

``` ruby
      # Also the docs submodule, if we're not building a --HEAD version
      if head?
        safe_system 'git', 'clone', 'doc/juliadoc', "#{dst}/doc/juliadoc"
      end
```

Judging by the comment, shouldn't it be `if !head?`? If I make that change I can successfully rebuild with the command above, but then again I'm not relying on it to build documentation.

**Comment by floringogianu** [comment]
@staticfloat unfortunately this breaks it when trying to build julia (not the --HEAD, but the regular version) from source. With the cache deleted and this commit reverted I could go on with the build without getting the docs submodule related error.

**Comment by staticfloat** [comment]
@floringogianu Good catch!  This is because the 0.3 branch [changed the way docs are handled](https://github.com/JuliaLang/julia/commit/8d864e1299d9c9b698314707082ba1de724e6142#diff-8903239df476d7401cf9e76af0252622) to be the same as 0.4.  I've [pushed a fix](https://github.com/staticfloat/homebrew-julia/commit/d08d0983bedb6f34fddc84cc9e6a4379f3d91441) to the formula, so this should be working for you now.  Thanks for the report.
