### ISSUE TITLE
'deps/utf8proc' does not exist when compiling julia --HEAD

### ISSUE THREAD

**Issue by techstep** [staticfloat/homebrew-julia#149]
I tried building julia --HEAD this morning, and I got the following message:

```
git clone deps/utf8proc /private/tmp/julia20150416-1676-fdzwnv/deps/utf8proc
fatal: repository 'deps/utf8proc' does not exist
Error: Failure while executing: git clone deps/utf8proc /private/tmp/julia20150416-1676-fdzwnv/deps/utf8proc
```
I'm not quite sure how to fix this problem. 

I've included the contents of the log files, and `brew config` and `brew doctor`, here:

https://gist.github.com/techstep/15ba46d68964bc3a5c52

**Comment by cyberbryce** [comment]
I'm having the same problem with 10.10.3. I deleted and reinstalled Homebrew, to no avail. I have a nearly identical configuration.

**Comment by dprn** [comment]
same issue here (10.10.3 and identical configuration)

**Comment by cyberbryce** [comment]
FYI, being anxious enough to (hopefully) improve the way in which tuples are used in my ongoing project, I went ahead and installed from source. I followed the LINUX instructions, ignoring external dependencies (which should have remained on my system) and internal dependencies (the error seems to have something to do with the restructuring of these) and crossing my fingers. I had to brew cmake to get it to work, but I doubt that has anything to do with this bug.

Without leaning on Elliot's brew per usual, it took a few hours. Thanks Elliot!

**Comment by cyberbryce** [comment]
(Btw, by thanks, I don't mean anything sarcastic! Not that kind of faceless internet conversation. I truly mean thanks. The time required to compile from scratch on my old machine shows how much time Elliot's work has been saving these past months.)

**Comment by staticfloat** [comment]
Hahaha, no problem.  I always try to interpret things in the benevolent sense.  :)

This is most likely an error with the way the Homebrew formula tries to deal with [checking out Julia's submodules](https://github.com/staticfloat/homebrew-julia/blob/8b5313d6c4e283b5be14855405e6fa6a41b2829b/julia.rb#L11-L19), as you can see we've got some hard-coded submodule names in there that need to be kept in sync with Julia upstream, but as far as I can tell, things are working as they should be.  The whole reason we need this code is because Homebrew stores git checkouts in its cache directory (`brew --cache` will show you where) and we need to keep our submodules stored there as well.  However, we [recently did away](https://github.com/JuliaLang/julia/commit/14840d63b249bacd98c855474270c73335af546b) with git submodules, and on new checkouts of the Julia git repository, we would run into this issue, as you all found out.

I've since [changed the formula](https://github.com/staticfloat/homebrew-julia/pull/151) to no longer attempt to do this git submodule skullduggery.

**Comment by cyberbryce** [comment]
Yes, that was the extent of it. The formula worked for the release as of a few hours ago. Thanks again, Elliot.
