### ISSUE TITLE
How to install both release and dev versions of Julia?

### ISSUE THREAD

**Issue by sje30** [staticfloat/homebrew-julia#168]
Hi,

Thanks for your work maintaining julia on homebrew.

Is there a way to install both the latest release (e.g. 0.3.11) and the current head of Julia using homebrew?  (with then e.g. "julia" running the latest version, and "julia-dev" running the head from the command line.)

**Comment by staticfloat** [comment]
Personally, I find it more useful to build the latest `HEAD` julia through source.  This is for two reasons;

* First, it's actually faster to `git pull && make` a new version of Julia that has been built from source than to use Homebrew.  This is because Homebrew always starts from scratch (note that it starts from scratch with _only_ Julia, not the dependencies, which is good!) which means that you have to spend some time waiting for code to finish compiling that you may or may not have actually needed if you were building from a previous build directory.

* Second, [recent changes to Homebrew](https://github.com/Homebrew/homebrew/issues/37091) have removed the ability for multiple versions of the same formula to co-exist in an easily-switchable fashion. This means that you would indeed need to do something like what you are suggesting with `julia` and `julia-dev` disambiguating the two,

If you really want to use Homebrew, here's where I would start:

* First, create a new formula file.  Just copy `julia.rb` to `juliadev.rb`, and change [this line](https://github.com/staticfloat/homebrew-julia/blob/4b5e9419433d9590594b0b577f372c320a160310/julia.rb#L24) to `Juliadev`.

* Next, you'll need to add lines renaming things to `juliadev` or whatever you want to call your secondary Julia executable.  Something like `mv "#{bin}/julia", "#{bin}/juliadev"` after [this line](https://github.com/staticfloat/homebrew-julia/blob/4b5e9419433d9590594b0b577f372c320a160310/julia.rb#L189) but before the final `end` of the `install` block.

It's possible that those modifications aren't enough, since other files might conflict between Julia 0.3 and 0.4, but those will just need to be renamed as well.  The failure will manifest as a failure to "link" the Julia keg due to files already existing with the same names.

**Comment by sje30** [comment]
Ok, thanks very much.  I'll follow your advice and go with the source route for building `HEAD`.
